databases/postgis3*: fix run
On i386, when WAGYU is enabled, the extension can not be installed:

Undefined symbol
ERROR: ... Undefined symbol ...
postgis 3.0 and 3.1: "_ZNKSt8__detail20_Prime_rehash_policy11_M_next_bktEj"
postgis 3.2: "_ZNSt8ios_base4InitD1Ev"

Postgis uses C++ libs and requires compiler:gcc-c++-lib option to
be loaded as a PostgreSQL extension.